language: julia

os:
  - linux

julia:
  - 1.0.5
  - 1.5.1
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

sudo: false

after_success:
  - julia -e 'if VERSION >= v"0.7.0-" using Pkg end; cd(Pkg.dir("DecisionTree")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
